### ISSUE TITLE
"unknown type" in Buffer.writeValues()

### ISSUE THREAD

**Issue by octo** [collectd/go-collectd#11]
Turns out that *Parse()* can handle `counter` metrics, but *Buffer.writeValues()* can't write them.

``` 
panic: unknown type

goroutine 1 [running]:
collectd.org/network.Fuzz(0x7fe8fa833000, 0xf, 0x200000, 0x10)
        /tmp/go-fuzz-build999482993/src/collectd.org/network/fuzz.go:47 +0x339
github.com/dvyukov/go-fuzz/go-fuzz-dep.Main(0x652568)
        /usr/local/google/home/octo/go/src/github.com/dvyukov/go-fuzz/go-fuzz-dep/main.go:47 +0x13d
main.main()
        /tmp/go-fuzz-build999482993/src/go-fuzz-main/main.go:10 +0x2a
```

**Comment by ryancox** [comment]
Fuzzing FTW!   You can list your fixes at the bottom of this page if you are so inclined: https://github.com/dvyukov/go-fuzz

**Comment by octo** [comment]
@ryancox I've added #10 to that list. I didn't add this one because it was an unexpected error, rather than an actual crash – you already took care of the *panic()* in #6 :-)
