### ISSUE TITLE
collectd server crashes with empty listening address or address without host part

### ISSUE THREAD

**Issue by juliusv** [collectd/go-collectd#12]
See https://github.com/prometheus/collectd_exporter/issues/18.

When calling `ListenAndWrite()` on a collectd server that has either an empty `Addr` or one that only contains the port (`:12345`), there's an index-out-of-range panic:

```
panic: runtime error: index out of range

goroutine 10 [running]:
net.IP.IsMulticast(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/ip.go:132 +0x9b
collectd.org/network.(*Server).ListenAndWrite(0xc2080505a0, 0x0, 0x0)
	/home/julius/gosrc/src/github.com/prometheus/collectd_exporter/.build/gopath/src/collectd.org/network/server.go:49 +0x125
main.func·001()
	/home/julius/gosrc/src/github.com/prometheus/collectd_exporter/main.go:248 +0x27
created by main.startCollectdServer
	/home/julius/gosrc/src/github.com/prometheus/collectd_exporter/main.go:249 +0x2a9
```

This is because `net.ResolveUDPAddr()` returns a `nil` IP when the host part is missing here:

https://github.com/collectd/go-collectd/blob/master/network/server.go#L43

Given this code:

https://github.com/collectd/go-collectd/blob/master/network/server.go#L38-L41

...it looks like the code is *intended* to work with empty / port-only addresses, so this looks like something that should be fixed in go-collectd.

**Comment by octo** [comment]
Thanks @juliusv!
