### ISSUE TITLE
Unable to send metrics using network.Client 

### ISSUE THREAD

**Issue by bryanvpham** [collectd/go-collectd#15]
I'm trying to send some metrics to a server from my application but I've been unsuccessful. I've been able to send it using CollectD just fine from the same location so it's likely not a networking issue. Is there something wrong with my code? I used your test_client.go to help me. Or is there an issue with the library?

```
package main

import (
    "collectd.org/api"
    "collectd.org/network"
    "collectd.org/exec"
    "net"
    "time"
    "log"
)

func main() {
	options := network.ClientOptions{
        SecurityLevel: network.Encrypt,
        Username: "my_username",
        Password: "my_password",
    }

    conn, err := network.Dial(net.JoinHostPort("23.x.x.x", "25825"), options)
    if err != nil {
		log.Fatal(err)
	}
    defer conn.Close()

	vl := api.ValueList{
		Identifier: api.Identifier{
			Host:   "testing.bryan",
			Plugin: "cpu",
			Type:   "cpu",
		},
        Time:     time.Now(),
        Interval: time.Second * 1,
        Values:   []api.Value{api.Gauge(42)},
	}    
    
    exec.Putval.Write(vl)

    for {
        if err := conn.Write(vl); err != nil {
            log.Fatal(err)
        }
        conn.Write(vl)
        log.Println("Metrics Sent")
        time.Sleep(time.Second * 1)
    }
}
```

This is the config for my network plugin for collectd
```
LoadPlugin network

<Plugin network>
        <Server "23.x.x.x" "25825">
                SecurityLevel "Encrypt"
                Username "my_username"
                Password "my_password"
        </Server>
</Plugin>
```

**Comment by octo** [comment]
Hi @bryanvpham, sorry for the late reponse :(

The *collectd* configuration you posted is the configuration for a client, i.e. that collectd will try to *send* metrics, not receive them. Therefore the metrics sent by your Go code are never received.

Other potential pitfalls: You're calling `conn.Write(vl)` twice – once with error checking and once without, so each iteration sends the same metric twice. Also, the metric isn't updated between iterations, you need to at least set `vl.Time = time.Now()` inside the loop.

Best regards,
—octo
