### ISSUE TITLE
Licensing terms

### ISSUE THREAD

**Issue by jerrygb** [collectd/go-collectd#31]
Hi @octo 

Could you please elaborate on the License for the project? Specifically interested in https://github.com/collectd/go-collectd/tree/master/plugin

Thank you!

**Comment by octo** [comment]
Hi, sorry for the late reply, I've been on leave for a couple of weeks.

The `plugin` package links this repository's code with code from collectd, so both licenses need to be considered. collectd is licensed under the [MIT license](https://opensource.org/licenses/MIT), this repository's code (including the `collectd.org/plugin` package) is licensed under the [ISC license](https://opensource.org/licenses/ISC), which is essentially the MIT license updated and simplified according to a changing legal landscape. [The MIT License, Line by Line](https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html) is the best resource I know discussing what the license says and what implications that has.

Is there any specific question you'd like cleared up?

Best regards,
—octo

**Comment by jerrygb** [comment]
Perfect @octo. I figured it was ISC based on the header. Good to make sure.

Thank you for the reply!

Regards,
Jerry

**Comment by octo** [comment]
You're welcome :)
