### ISSUE TITLE
conversion error message is too opaque to action

### ISSUE THREAD

**Issue by yellowpattern** [collectd/go-collectd#32]
When go-collectd is used inside of influxdb, there can be 10s of servers sending 100s of metrics in and only one reports an error. The error message as it stands is like this:

`2017/09/07 16:55:07 unable to convert values according to TypesDB: len(args) = 3, want 4
`

There are not enough details present to properly troubleshoot the situation.

This patch:

```
diff -u ./go-collectd/network/parse.go ./go/src/collectd.org/network/parse.go
--- ./go-collectd/network/parse.go	2017-09-08 19:32:59.949965463 +1000
+++ ./go/src/collectd.org/network/parse.go	2017-09-08 23:18:41.574964616 +1000
@@ -110,7 +110,7 @@
 				// Returns an error if the number of values is incorrect.
 				v, err := ds.Values(ifValues...)
 				if err != nil {
-					log.Printf("unable to convert values according to TypesDB: %v", err)
+					log.Printf("unable to convert metric %v values %v according to %v in TypesDB: %v", state, ifValues, ds, err)
 					continue
 				}
 				vl.Values = v
```

Produces a message like this:

`2017/09/08 23:15:11  unable to convert metric hostname/plugin-instance/type-type_instance values [0 20690 0 48630396 0] according to &{type [{field1 api.Counter 0 NaN} {field2 api.Counter 0 NaN} {field3 api.Counter 0 NaN} {field4 api.Counter 0 NaN} {bytesdrop api.Counter 0 NaN} {field5 api.Counter 0 NaN}]} in TypesDB: len(args) = 5, want 6`

... which I can then track down to a source very easily. Possibly the text presentation of "ds" is more detailed than it needs to be, but this doesn't get in the way of resolving the problem.

**Comment by octo** [comment]
Hi @yellowpattern, thanks for opening this issue! You solution looks okay, can you turn it into a pull request? See also: [Creating a pull request](https://help.github.com/articles/creating-a-pull-request/)

Thanks and best regards,
—octo
