### ISSUE TITLE
collectd.org is down

### ISSUE THREAD

**Issue by h8liu** [collectd/go-collectd#37]
says "refuse to connect".

`go get collectd.org` hence does not work.

**Comment by icebergwater** [comment]
same problem +1

**Comment by RenEvo** [comment]
> Ouch, sorry about that! Hardware upgrade went a little haywire, I'm working on getting the site back up ASAP —@flocto
12:06 AM - 19 Jul 2018

**Comment by glinton** [comment]
Is there any chance you remove the [import comments](https://github.com/collectd/go-collectd/blob/master/api/main.go#L2) (`// import "collectd.org/api"
`) that force the vanity URL? It would be nice to simply import `github.com/collectd/go-collectd`

**Comment by rpv-tomsk** [comment]
Florian, can you please fix WIKI ?

https://collectd.org/wiki/ is down, server responding with `403 Forbidden`.

**Comment by rpv-tomsk** [comment]
New issue created specially for WIKI's inaccessibility : https://github.com/collectd/collectd/issues/2868
So, close this. )
