### ISSUE TITLE
Guidance on reading collectd xml

### ISSUE THREAD

**Issue by MovieStoreGuy** [collectd/go-collectd#40]
As I understand it, most collectd monitors allow them to be configurable by defining a XML definition.

I was wonder if that assumption is correct and how you would write a plugin to understand those values.

Any advice would be wonderful

**Comment by octo** [comment]
Hi Sean,

collectd can be configured with a configuration file. The format borrows heavily from the Apache Webserver's configuration format.

It is not yet possible to configure Go plugins through this config file, but there is work underway to add that support, see #30.

Best regards,
—octo
