### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by SuperQ** [collectd/go-collectd#77]
It looks like it's been a long time since a release was tagged. With Go modules, git tags are used to lock vendoring by default. There's [a lot of changes](https://github.com/collectd/go-collectd/compare/v0.3.0...master). Maybe time to cut a new version.

**Comment by octo** [comment]
+1, a new release is overdue.

**Comment by octo** [comment]
There you go, thanks for nudging me :)

https://github.com/collectd/go-collectd/releases/tag/v0.4.0

**Comment by SuperQ** [comment]
Thanks! Bumping it in the collectd_exporter

https://github.com/prometheus/collectd_exporter/pull/94
