### ISSUE TITLE
RFC: Repo location for 'Go' based plugins

### ISSUE THREAD

**Issue by sunkuranganath** [collectd/go-collectd#79]
There was a discussion on mailing list based on @octo 's RFC now that collectd.org/plugin is available. Moving this to github to enable better conversation and possibly make a decision soon.

Two aspects that were raised in the mailing list:
- For Go-based plugins, i.e. plugins based on "collectd.org/plugin", create a separate repository, e.g. 
github.com/collectd/go-plugins, and maintain those there
- Instead unify the golang plugins and go-collectd packages under same directory structure. Meaning provide a home for golang plugins under "github.com/collectd/go-collectd/plugins". This would mean either moving "collectd.org/plugin" to another location or renaming it.

Thoughts?

**Comment by octo** [comment]
I favor a separate repository.

I have created [github.com/octo/go-plugins](https://github.com/octo/go-plugins) as a staging area for this. I was planning to eventually move this repository to the "collectd" organization. If I don't hear any opposition in the community call later today, I'll make the move tonight.

Best regards,
—octo

**Comment by sunkuranganath** [comment]
If having a separate repo makes thins easier overall, no objections from me.

**Comment by octo** [comment]
Done: https://github.com/collectd/go-plugins
