### ISSUE TITLE
Cannot perform fuzzing in external applications which include `collectd.org/network`

### ISSUE THREAD

**Issue by p-zak** [collectd/go-collectd#93]
**Cannot perform fuzzing in external applications (using `gofuzz` build tag) which include `collectd.org/network`.**

It is caused by `network/fuzz.go` failing:
```
> go test -v -tags gofuzz ./network/... 
network/fuzz.go:43:20: not enough arguments in call to s1.Write
        have (*api.ValueList)
        want (context.Context, *api.ValueList)
network/fuzz.go:58:20: not enough arguments in call to s2.Write
        have (*api.ValueList)
        want (context.Context, *api.ValueList)
```

It has been failing since this change: https://github.com/collectd/go-collectd/pull/21/files:
Two calls in `network/fuzz.go` to `func (b *Buffer) Write(_ context.Context, vl *api.ValueList) error` don't contain `context.Context` argument.

**Comment by eero-t** [comment]
@octo Shouldn't e.g. `go vet` (in https://github.com/collectd/go-collectd/blob/master/.travis.yml) catch issues like this:
> ```
> > go test -v -tags gofuzz ./network/... 
> network/fuzz.go:43:20: not enough arguments in call to s1.Write
>         have (*api.ValueList)
>         want (context.Context, *api.ValueList)
> network/fuzz.go:58:20: not enough arguments in call to s2.Write
>         have (*api.ValueList)
>         want (context.Context, *api.ValueList)
> ```
