### ISSUE TITLE
Cannot install `collectd.org/api`

### ISSUE THREAD

**Issue by jefchien** [collectd/go-collectd#95]
Reported to https://github.com/collectd/collectd.github.io/issues/3 since I believe the issue was caused by the most recent deployment, but linking it here for awareness.

Installation of the package appears broken.

```sh
> go get collectd.org
go: unrecognized import path "collectd.org": parse https://collectd.org/?go-get=1: no go-import meta tags ()

> go get collectd.org/api
go: unrecognized import path "collectd.org/api": reading https://collectd.org/api?go-get=1: 404 Not Found
```

**Comment by octo** [comment]
Hi @jefchien, thanks for flagging. This is likely a result of our move of `collectd.org` to GitHub Pages. I'll look into a fix for it.

**Comment by octo** [comment]
Oh, I see you already opened collectd/collectd.github.io#3, thanks for that! I'll keep both open for visibility.

**Comment by octo** [comment]
This issue has been fixed by adding the appropriate meta header to the website.
